### ISSUE TITLE
`/xkcd spiders` does not show spiders

### ISSUE THREAD

**Issue by belden** [hmemcpy/xkcd-slackbot#5]
Despite multiple spiders comics existing within the early history of XKCD, `/xkcd spiders` favors comic 136 over any of the ones that are more obviously related to spiders.

**Comment by hmemcpy** [comment]
Interesting! Looks like the first Google result for 'xkcd spiders' is https://what-if.xkcd.com/136/
The bot should ignore results from any subdomains other than the root xkcd.com

Thanks, I'll try and tweak it!

**Comment by belden** [comment]
The actual result that was returned to me was [!!!NSFW!!! xkcd.com/136](http://xkcd.com/136) which at first blush is pretty unrelated to spiders.

I am still blushing.

**Comment by belden** [comment]
As a side note, I set up a Google CSE as documented in the Readme.md (i.e. restricted to the xkcd.com site), and did not receive surprising results for `spiders`.

**Comment by hmemcpy** [comment]
Oh wow, that's nasty :)
I've set the google search link to match exactly xkcd.com/*/
![image](https://cloud.githubusercontent.com/assets/601206/15228526/3df5655e-1895-11e6-93c6-a7c5c2787135.png)

This should at least prevent any other links that are not comics.
I'll update the readme...
